"""empty message

Revision ID: 35051d041b1a
Revises: 84a8d9752293
Create Date: 2024-03-27 11:08:50.212075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35051d041b1a'
down_revision = '84a8d9752293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
