"""added book_id to Message class

Revision ID: 356fa251c895
Revises: 92a4c0c6e11b
Create Date: 2024-04-09 17:14:01.702620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356fa251c895'
down_revision = '92a4c0c6e11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###
