"""empty message

Revision ID: 884450b5da67
Revises: 21c69c5f8bbe
Create Date: 2024-04-07 15:55:47.349091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884450b5da67'
down_revision = '21c69c5f8bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_req', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('return_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_req', schema=None) as batch_op:
        batch_op.drop_column('return_date')
        batch_op.drop_column('issue_date')

    # ### end Alembic commands ###
