"""req_days can't be null


Revision ID: dc8d878f052f
Revises: 884450b5da67
Create Date: 2024-04-07 15:57:03.227694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8d878f052f'
down_revision = '884450b5da67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_req', schema=None) as batch_op:
        batch_op.alter_column('req_days',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_req', schema=None) as batch_op:
        batch_op.alter_column('req_days',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
